---
ID: "577005c4-bfff-42e8-95a4-20f07679e7dd"
Parent: "3363f60e-3756-4241-9a16-40386f6a3f46"
Template: "3363f60e-3756-4241-9a16-40386f6a3f46"
Path: /sitecore/templates/Modules/Sitecron/SiteCron Execution Reports Folder/__Standard Values
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Value: 1
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180328T142111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce768401-bf1a-4609-b9df-19bb1b74f68b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180328T184331Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180328T142111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce768401-bf1a-4609-b9df-19bb1b74f68b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180328T184331Z
