---
ID: "512da5be-ae7c-41fc-89d6-210193336e17"
Parent: "0dea17e8-b084-414d-b1cd-764602c58eae"
Template: "0dea17e8-b084-414d-b1cd-764602c58eae"
Path: /sitecore/templates/Modules/Sitecron/Sitecron Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0DEA17E8-B084-414D-B1CD-764602C58EAE}
    {7F2C8881-6AE4-48CF-A499-7745CC4B2EB2}
    {49A27DC8-2A6A-48A2-A8EF-02A3DD0D3274}
    {B9B437B2-789C-48F6-AAE2-B49C4AA2A4BB}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150620T160429
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c106abb7-481f-4254-b619-9f2bc78d1363"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180409T205510Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150620T160429
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c106abb7-481f-4254-b619-9f2bc78d1363"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180409T205510Z
