---
ID: "86eaa574-1af8-4562-a6e1-a158fb21ddbd"
Parent: "49a27dc8-2a6a-48a2-a8ef-02a3dd0d3274"
Template: "49a27dc8-2a6a-48a2-a8ef-02a3dd0d3274"
Path: /sitecore/templates/Modules/Sitecron/SiteCron Run As Sitecore Job/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T184925Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db73098f-8046-4ebd-99f9-5fa1be7d0578"
    - ID: "8d9bf9d3-9589-4749-a32e-5e04f7ca0f1f"
      Hint: SitecoreJobType
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180409T184951Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180409T184925Z
    - ID: "4ec306b1-4aa7-4bdd-a0b2-a3bb38e9fa0c"
      Hint: Type
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "db73098f-8046-4ebd-99f9-5fa1be7d0578"
    - ID: "8d9bf9d3-9589-4749-a32e-5e04f7ca0f1f"
      Hint: SitecoreJobType
      Value: Sitecron.Jobs.SitecoreJob.RunAsSitecoreJob, Sitecron
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180409T184951Z
